### ISSUE TITLE
Picture clarity problem

### ISSUE THREAD

**Issue by ccworld1000** [timo/cairo-p6#17]
![pie png](https://raw.githubusercontent.com/ccworld1000/CCChart/master//doc/screenshot/default.png)

Picture clarity problem?

In drawing up the pie chart, you can see the problem by enlarging the picture, and what is the way to deal with it clearly?

Just uploaded the code to [CCChart](https://github.com/ccworld1000/CCChart).

**Comment by ccworld1000** [comment]
![Uploading 7016AB6C-AAAB-48BF-AA77-9C8C2ADC51A6.png…]()

Location 1 looks fine. The others don't look so good.

**Comment by timo** [comment]
you can try playing around with the antialias mode:

    .antialias(ANTIALIAS_NONE);
    .arc(...);
    .fill();

will prevent pixels from taking on "half-colors",

`ANTIALIAS_BEST` also exists, for example.

In general, it's best to antialias using the subpixel order of the display in use, but of course you can't know what kind of monitor your .png is going to be displayed on at the point you're generating it.

Another advice I have is to use colors that are not 100% saturated, i.e. mix in a little bit of red and blue into your green, and have green at 90% instead of 100%

**Comment by ccworld1000** [comment]
It doesn't seem to work if I call it(ANTIALIAS_BEST).
 And the problem of text clarity.

![8ef41af0-5044-453e-8dad-876bdeb4b45b](https://user-images.githubusercontent.com/22360168/48842745-05bc3100-edd0-11e8-9f76-fe087023ff9c.png)

**Comment by ccworld1000** [comment]
the origin png file 
![png](https://raw.githubusercontent.com/ccworld1000/CCColor/master/doc/screenshot/colors.png)

**Comment by dwarring** [comment]
Is rendering to SVG an option? This is a vector format; as opposed to PNG which is a raster format. Both text and graphics should scale better:

For an example, see [svg-surface.p6](https://github.com/timo/cairo-p6/blob/master/doc/examples/svg-surface.p6)

**Comment by ccworld1000** [comment]
Thank you! At present, the main consideration is the PNG format, if there is no way, then I have to try the SVG format, or find other ways to deal with it.
